databases:
  - name: postgres
    databaseName: postgres_sfxp
    user: tructest

 services:
 - type: pserv
   name: pgbouncer
   env: docker
   plan: starter plus
   repo: https://github.com/render-oss/docker-pgbouncer
   envVars:
   - key: postgres://tructest:Wy22xIVR3Y2WJUr184hDDd5fMYRgefED@dpg-cdr4a6en6mpqj2ddu2b0-a/postgres_sfxp
     fromDatabase:
       name: postgres
       property: connectionString
   - key: POOL_MODE
     value: transaction
   - key: SERVER_RESET_QUERY
     value: DISCARD ALL
   - key: MAX_CLIENT_CONN
     value: 500
   - key: DEFAULT_POOL_SIZE
     value: 50