export const GET_NAVIGATION = 'NAV_GET_NAVIGATION';
export const GET_NAVIGATION_ERROR = 'NAV_GET_NAVIGATION_ERROR';
export const GET_NAVIGATION_SUCCEEDED = 'NAV_GET_NAVIGATION_SUCCEEDED';

export const GET_DETAIL = 'NAV_GET_DETAIL';
export const GET_DETAIL_ERROR = 'NAV_GET_DETAIL_ERROR';
export const GET_DETAIL_SUCCEEDED = 'NAV_GET_DETAIL_SUCCEEDED';

export const GET_LINKS = 'NAV_GET_LINKS';
export const GET_LINKS_ERROR = 'NAV_GET_LINKS_ERROR';
export const GET_LINKS_SUCCEEDED = 'NAV_GET_LINKS_SUCCEEDED';

export const SET_LINKS = 'NAV_SET_LINKS';

export const CHANGE_CATEGORY = 'NAV_CHANGE_CATEGORY';
export const ADD_CATEGORY = 'NAV_ADD_CATEGORY';

export const SAVE_NAVIGATION = 'NAV_SAVE_NAVIGATION';
export const SAVE_NAVIGATION_ERROR = 'NAV_SAVE_NAVIGATION_ERROR';
export const SAVE_NAVIGATION_SUCCEEDED = 'NAV_SAVE_NAVIGATION_SUCCEEDED';


export const NEW_POPUP_CHANGE = 'ZALO_NEW_POPUP_CHANGE';
export const NEW_POPUP_SAVE = 'ZALO_NEW_POPUP_SAVE';
